version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - /tmp/shift-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shift
      - MYSQL_USER=shift
      - MYSQL_PASSWORD=shift
  shift:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://shift:shift@db/shift?pool=30&timeout=5000
      - SECRET_KEY_BASE=some_random_30_char_string
      - UI_ADMINS=cadl
      - UI_MYSQL_USER=shift
      - UI_MYSQL_PASSWORD=shift
      - RUNNER_MYSQL_USER=root
      - RUNNER_MYSQL_PASSWORD=root
