version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  shift:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://root:root@db/shift?pool=30&timeout=5000
      - SECRET_KEY_BASE=some_random_30_char_string
      - SHIFT_ADMINS=cadl,admin,UNKNOWN
      - SHIFT_STOP_FILE_PATH=/var/lib/shift/control/stop
      - SHIFT_OSC_MYSQL_PASSWORD=root
      - SHIFT_OSC_MYSQL_USER=root
    depends_on:
      - db